### ISSUE TITLE
Problem in setup jsbsim SITL with Cygwin in windows 

### ISSUE THREAD

**Issue by moreba1** [Auterion/px4-jsbsim-bridge#41]
I installed the Cygwin and cloned px4 then installed rolling release of jsbsim on windows.
when i run px4 SITL (HEADLESS=1 make px4_sitl jsbsim_rascal) i get this error:

![1](https://user-images.githubusercontent.com/14200369/100514379-81a09f00-3189-11eb-878e-336ac8e5ca5c.JPG)
![2](https://user-images.githubusercontent.com/14200369/100514382-85342600-3189-11eb-9a85-ef06a1bcdad7.JPG)

**Comment by Jaeyoung-Lim** [comment]
@moreba1 Your log seems to say you are missing a few libraries have you tried installing them?

I would be more than happy if you could contribute this project to work on windows, but given that said, this project is not expected to work out of the box in windows. Is there any specific reason that you are trying to run windows?
