### ISSUE TITLE
JSBSIM not found 

### ISSUE THREAD

**Issue by pbecchi** [Auterion/px4-jsbsim-bridge#53]
Hi,
I succesfully compile and build JSBSim in Ubuntu 32 bit.

When I try to build PX4:
`HEADLESS=1 make px4_sitl jsbsim_quadrotor_x`
i got the message JSBSIM not found.

I have updated  $PATH adding JSBSim directory ("/jsbsim/build/src") but this doesnt solve the problem.
Thanks for your help.

**Comment by Jaeyoung-Lim** [comment]
@pbecchi Can you confirm that you have installed jsbsim?

**Comment by pbecchi** [comment]
Yes, It has been built and tested using the line command. 
Initially I thought that "not found" was due to $PATH , but now the jsbsim directory has been added to it .....
The message is still there. 
Thanks

**Comment by pbecchi** [comment]
I have found that jsbsim was not correctly installed.
Now px4-sitl build succesfully!
Thanks

**Comment by Jaeyoung-Lim** [comment]
@pbecchi Thanks for the update!
