### ISSUE TITLE
multi vehicle support in px4 jsbsim-bridge

### ISSUE THREAD

**Issue by airsimdevdd** [Auterion/px4-jsbsim-bridge#54]
any multi vehicle support in jsbsim bridge @Jaeyoung-Lim

**Comment by Jaeyoung-Lim** [comment]
@airsimdevdd Could you please clarify what multivehicle support means in this context?

Are you trying to run multiple vehicles in a single jsbsim instance? or are you just talking about simulating multiple vehicles at once in parallel?

if it is the latter, you can already do this by creating a script to launch multiple instances of SITL

**Comment by airsimdevdd** [comment]
simulating multiple vehicles at once in parallel sir

**Comment by Jaeyoung-Lim** [comment]
@airsimdevdd could you clarify what does at once mean? The two examples are both simulating "at once"

**Comment by airsimdevdd** [comment]
Sir ,I want to fly two or more vehicle simultaneously in sitl

**Comment by ParamDeshpande** [comment]
any updates on this ? I want a single jsbsim simulation and mulitiple PX4 instances ( planes ) running inside this one simulation. I'm looking for lightweight simulations and JSBsim does the job, other methods are too RAM and resource intensive for multi-vehicle single-simulator simulations.  I'm looking to get HITL setup up and running for this, but to get started an SITL setup would be helpful too. Thanks !

**Comment by Jaeyoung-Lim** [comment]
@ParamDeshpande You probably need multiple instances of jsbsim running in order to simulate multiple vehicles

**Comment by ParamDeshpande** [comment]
@Jaeyoung-Lim   Thanks ! Got the SITL multi-plane simulation up and running.
