### ISSUE TITLE
HITL, No GPS Lock for Vehicle over serial 

### ISSUE THREAD

**Issue by ParamDeshpande** [Auterion/px4-jsbsim-bridge#61]
I have followed the instructions from this [PR](https://github.com/Auterion/px4-jsbsim-bridge/pull/28) to enable HITL support for JSB-Sim bridge and am able to connect to the JSBSim-bridge via serial port. 
I am facing the following issue in HITL mode.
`No GPS Lock for Vehicle : `

![Screenshot from 2022-11-03 18-30-16](https://user-images.githubusercontent.com/37805111/199727100-436c76d9-1cca-4c2c-b9bf-ed577a1386bc.png)

 I have selected the airplane configuration as HILStar (XPlane), on the [cubepilot cubeorange ADSB module](https://ardupilot.org/copter/docs/common-thecubeorange-overview.html). I am using the PX4-Autopilot version 1.12.3.

Any suggestions ?

**Comment by ParamDeshpande** [comment]
I've solved this issue, the GPS lock can be enabled by setting 
`interface->SetHILStateLevel(false);` in the file `jsbsim_bridge.cpp` from this [PR](https://github.com/Auterion/px4-jsbsim-bridge/pull/28)

**Comment by Jaeyoung-Lim** [comment]
@ParamDeshpande Great! Would it be possible to make a PR on the branch?

**Comment by ParamDeshpande** [comment]
@Jaeyoung-Lim  Sure, I've created the PR on the HIL branch.
